import { WebsiteHeader } from "@/app/(landingPages)/_components/header/WebsiteHeader";
import { WebsiteHeaderMobile } from "@/app/(landingPages)/_components/header/WebsiteHeaderMobile";
import type { Metadata } from "next";
import { UTMInit } from "@roo/shared/src/functions/analytics/UTMInit";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function BlogLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <UTMInit />
      <div className="flex flex-col">
        <WebsiteHeader />
        <WebsiteHeaderMobile />
        {children}
      </div>
    </>
  );
}
