import type { Metadata } from "next";
import "./_css/animations.css";
import "./globals.css";

import { GoogleTagManager } from "@next/third-parties/google";
import Footer from "./_components/footer/Footer";
import Header from "./_components/header/Header";
import StoreProvider from "./_redux/StoreProvider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="cs">
      <GoogleTagManager gtmId="" />
      <body>
        <StoreProvider>
          <Header />
        </StoreProvider>
        <div className="relative">
          {children}
          <Footer />
        </div>
      </body>
    </html>
  );
}
