import type { Metadata } from "next";
import "./_css/animations.css";
import "./_css/globals.css";

import { GoogleTagManager } from "@next/third-parties/google";
import Footer from "./_components/footer/Footer";
import Header from "./_components/header/Header";
import StoreProvider from "./_redux/StoreProvider";
import AuthModal from "./_components/molecules/modals/AuthModal/AuthModal";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="cs">
      <GoogleTagManager gtmId="" />
      <body className="min-h-screen h-full flex flex-col">
        <StoreProvider>
          <Header />
          <AuthModal />
        </StoreProvider>
        <main className="flex-1 flex flex-col h-full">{children}</main>
        <Footer />
      </body>
    </html>
  );
}
