import type { Metadata } from "next";
import "./globals.css";
import Header from "./_global/header/Header";
import StoreProvider from "./_redux/StoreProvider";
import Footer from "./_global/footer/Footer";
import ContentWrapper from "./_global/wrappers/ContentWrapper";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="cs">
      <body>
        <StoreProvider>
          <Header />
        </StoreProvider>
        <div className="relative">
          {children}
          <Footer />
        </div>
      </body>
    </html>
  );
}
