import type { Metadata } from "next";
import { AdminHeader, AdminSidebar } from "./page";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function AdminLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <body>
      <div className="grid grid-cols-[110px_1fr]">
        <AdminSidebar />
        <div className="bg-zinc-100">
          <AdminHeader />
          <div className="p-10">{children}</div>
        </div>
      </div>
    </body>
  );
}
