import type { Metadata } from "next";
import { AdminSidebar } from "./_components/AdminSidebar";
import { AdminHeader } from "./_components/AdminHeader";
import StoreProvider from "../_redux/StoreProvider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function AdminLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <body>
      <StoreProvider>
        <div className="grid grid-cols-[70px_1fr] h-screen bg-zinc-150 pr-4">
          <AdminSidebar />
          <div className="h-[97%] self-center overflow-y-hidden border border-borderLight flex flex-col shadow-lg rounded-large bg-zinc-100 p-4">
            {children}
          </div>
        </div>
      </StoreProvider>
    </body>
  );
}
