import type { Metadata } from "next";
import { AdminSidebar } from "./_components/AdminSidebar";
import { AdminHeader } from "./_components/AdminHeader";
import StoreProvider from "../_redux/StoreProvider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function AdminLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <body>
      <StoreProvider>
        <div className="grid grid-cols-[90px_1fr]">
          <AdminSidebar />
          <div className="bg-zinc-100 h-screen flex flex-col">
            <AdminHeader />
            {children}
          </div>
        </div>
      </StoreProvider>
    </body>
  );
}
