import type { Metadata } from "next";
import "./globals.css";
import Header from "./_components/global/header/Header";
import StoreProvider from "./_redux/StoreProvider";
import Footer from "./_components/global/header/Footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <StoreProvider>
        <body>
          <Header />
          <div className="pt-60">{children}</div>
          <Footer />
        </body>
      </StoreProvider>
    </html>
  );
}
