import type { Metadata } from "next";
import "./globals.css";
import Header from "./_components/global/header/Header";
import StoreProvider from "./_redux/StoreProvider";
import Footer from "./_components/global/header/Footer";
import ContentWrapper from "./_components/wrappers/ContentWrapper";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <div className="relative">
          <StoreProvider>
            <Header />
          </StoreProvider>
          {children}
          <Footer />
        </div>
      </body>
    </html>
  );
}
