import type { Metadata } from "next";
import { AdminMenu } from "./_components/AdminMenu";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function AdminLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className="grid md:grid-cols-[70px_1fr] max-md:flex flex-col-reverse h-screen bg-zinc-150 md:pr-4 max-md:pt-2 max-md:px-2">
      <AdminMenu />
      <div className=" w-full md:h-[97%] h-full self-center overflow-y-hidden border border-borderLight flex flex-col shadow-lg rounded-lg bg-zinc-100">
        {children}
      </div>
    </div>
  );
}
